### PR TITLE
Make configurable execution console url

### PR DESCRIPTION
**Pull request by ddl-rliu**
## Tracking issue
https://github.com/flyteorg/flyte/issues/5641

## Why are the changes needed?

This is a downstream PR corresponding to the upstream PR: https://github.com/flyteorg/flytekit/pull/2661

## Check all the applicable boxes 

- [ ] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] All commits are signed-off.

### CODE REVIEW

**Comment by ddl-ebrown** [comment]
1 - Let's see if we can get buy-in from upstream
2 - Is it possible (or desirable) to emit *multiple* links?

**Comment by ddl-rliu** [comment]
Updated: upstream PR https://github.com/flyteorg/flytekit/pull/2661 and upstream issue https://github.com/flyteorg/flyte/issues/5641

Re: multiple links – the upstream PR has an example of what this now looks like.

```
$ pyflyte run --remote wf.py wf --a 1 --b 1
...
[✔] Go to https://.../domains/development/executions/amazingly-many-cockatoo-u99k to see the
execution in the console.
    Go to https://<url-with-additional-info>/amazingly-many-cockatoo-u99k to see the execution in Domino.
```

**Comment by ddl-ebrown** [comment]
FYI - there's a 1.13.2 now.

I created the branch https://github.com/dominodatalab/flytekit/tree/1.13.2-domino, pushed up all the tags from upstream and changed the base branch for this PR.

Looks like you're going to need to rebase this PR given some upstream changes

**Comment by ddl-ebrown** [comment]
We should probably update the GH actions somewhere to stop running irrelevant things -- but that gets tricky in a fork.

Have we gotten any buy-in upstream on this approach yet?

**Comment by ddl-ebrown** [comment]
Ok, we've got another new branch -- https://github.com/dominodatalab/flytekit/commits/1.13.3-domino/

I retargeted - will let you repush the branch

**Review by ddl-ebrown — APPROVED** [review]

**Pull request merged**
